### ISSUE TITLE
Makefile syntax error

### ISSUE THREAD

**Issue by sjc960115** [cloudera/yunikorn-web#4]
Makefile:56: *** missing separator.  Stop.

**Comment by yangwwei** [comment]
Ah, there was a missing colon causing this problem.
Thanks for pointing this out @sjc960115 !

**Comment by sjc960115** [comment]
> Ah, there was a missing colon causing this problem.
> Thanks for pointing this out @sjc960115 ! Do you want to help us to fix this issue with a PR?
> Thank you
https://github.com/cloudera/yunikorn-web/pull/5

**Comment by yangwwei** [comment]
this is resolved by #5

**Comment by yangwwei** [comment]
Hi @sjc960115 

Thanks for your contribution to the project. Can you please follow https://github.com/cloudera/yunikorn-core/blob/master/docs/how-to-contribute.md to sign and return us an ICLA? Literally, this PR should not be merged before that, apologies I forgot this at the first place. Sorry for the inconvenience.
